import "./globals.css";
import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { Lexend } from "next/font/google";
config.autoAddCss = false;
export const metadata = {
  title: "SundaCode",
  description: "Generated by sundacode entertainment",
};
const lexend = Lexend({ subsets: ["latin"] });
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head></head>
      <body className={lexend.className}>{children}</body>
    </html>
  );
}
