import "./globals.css";
export const metadata = {
  title: "SundaCode",
  description: "Generated by sundacode entertainment",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>SundaCode</title>
        <link
          rel="SundaCode icon"
          href="./svg/logo-sundacode.svg"
          type="image/x-icon"
        ></link>
      </head>
      <body>{children}</body>
    </html>
  );
}
